title: Full Stack Political Science
description: A blog about becoming your own IT division as a social science researcher
author: Musashi (Jacobs-) Harukawa
github: https://github.com/muhark
about: Coding, Debugging, Designing and Optimizing for Political Science Research

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/MJacobsHarukawa"
    - icon: fa-linkedin
      link: "www.linkedin.com/in/musashijacobsharukawa"
    - icon: fa-github
      link: "https://github.com/muhark"

share:
  twitter_username: MJacobsHarukawa

urls:
    - text: About
      url: /about/
    - text: Research and Projects
      url: /projects/
    - text: Teaching Website
      url: /dpir-intro-python/index.html
    - text: XML Feed
      url: /feed.xml

url: "https://muhark.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-jupyter-notebook

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
